### ISSUE TITLE
Command asking input during execution

### ISSUE THREAD

**Issue by deather** [oh-my-fish/plugin-foreign-env#14]
Hi,

During my tests to fixing issue on my plugin, I found an issue (or not) on fenv. I try to use fenv with sdkman.
For certain reasons, the command asks some input like (Would you like to update Y/N ?).

The problem is the default output is not forwarding to the main process. The default input is with ^&1.

A simple solution could be to forward it, but I don't know if it is the best idea. It could be most smart to configure it with parameter.

I hope you can understand me. Thanks for reading.

**Comment by gordolio** [comment]
I experience this problem when trying to use the sdkman plugin with fish. When I run `sdk install java 17.0.2-tem` it seems to hang. When it actually is prompting me if I want to set it as the default. The only way I knew this was the problem by trying to run the same `sdk install` command in zsh.
