### ISSUE TITLE
"%s" in env var

### ISSUE THREAD

**Issue by jab** [oh-my-fish/plugin-foreign-env#3]
Say `foo.sh` has:

``` sh
#!/bin/sh
export FOO="hello, %s"
```

I want `fenv source foo.sh` to set the environment variable `FOO` to the literal value `"hello, %s"`. Instead it's getting set to something weird like `15654 15253 15251...`. Can you tell what's going on, and is it possible to get this to work?

**Comment by derekstavis** [comment]
Hm. That's a side effect of using `printf`. I will try to figure out the issue. Thanks for the report.

**Comment by jab** [comment]
My pleasure, thanks for taking a look. Is there anything I can do to work around this in the meantime?

**Comment by derekstavis** [comment]
This should be fixed in master. I'm closing this issue for now. Feel free to comment if you happen to find this issue again. Thanks for the report!!
